modLoader="javafml"
loaderVersion="[47,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="edible_heart"
version="1.0.0"
displayName="Edible Heart"
displayURL="https://mcreator.net"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="36101, MCreator"
description="Adds edible hearts and a few more."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.edible_heart]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



